when:
  instance: ci.kokuwa.io
  repo: woodpecker/dockerhub-metadata
  event: [manual, push, pull_request]
  branch: main
  path: [.woodpecker/build.yaml, Dockerfile, Dockerfile.dockerignore, entrypoint.sh]

depends_on: [build]
matrix:
  PLATFORM: [amd64, arm64]
labels:
  platform: linux/${PLATFORM}

steps:

  pr:
    image: registry.kokuwa.io/kokuwaio/dockerhub-metadata:ci-${CI_PIPELINE_NUMBER}
    commands: curl https://hub.docker.com/v2/namespaces/kokuwaio/repositories/dockerhub-metadata/tags --silent --fail | jq
    when:
      event: pull_request

  kokuwa.io: &version
    image: registry.kokuwa.io/kokuwaio/dockerhub-metadata
    pull: true
    commands: curl https://hub.docker.com/v2/namespaces/kokuwaio/repositories/dockerhub-metadata/tags --silent --fail | jq
    when:
      event: [manual, push]
      branch: main

  docker.io:
    image: docker.io/kokuwaio/dockerhub-metadata
    <<: *version

  ghcr.io:
    image: ghcr.io/kokuwaio/dockerhub-metadata
    <<: *version
